### ISSUE TITLE
Usecase

### ISSUE THREAD

**Issue by Snowmanko** [theeternalsw0rd/laravel-nginx-rtmp#1]
I just want to ask you what this application does.

Thanks!

**Comment by theeternalsw0rd** [comment]
I developed it for livestreaming. It has an rtmp service so a video feed can be sent to it. It generates a multiple bitrate HLS playlist. It can also push an rtmp copy over to Facebook. It worked but overloaded my server, so I had to stop development.

**Comment by Snowmanko** [comment]
Thanks for clarification, I am looking for some PHP implementation that is able to create RTMP stream..
